#!/bin/bash

if [ ! -d "dep" ]; then
  mkdir dep
fi

if [ ! -d "bin" ]; then
  mkdir bin
fi

if [ ! -d "dump" ]; then
  mkdir dump
fi

if [ ! -d "vmh" ]; then
  mkdir vmh
fi

mv *.d dep/
mv parc* bin/
for x in bin/*;do maven-objdump -D --disassemble-zeroes --section=.xcpthandler --section=.text --section=.data $x > $x.dump;done
mv bin/*.dump dump/
for x in dump/*;do python ../scripts/objdump2vmh.py -f $x;done
mv dump/*.vmh vmh/
