#!/usr/bin/env python
#=========================================================================
# pex-regincr-sim [options] <input>
#=========================================================================
#
#  -h --help     Display this message
#  -v --verbose  Verbose mode
#
# The register/incrementer simulator
#
# Author : Christopher Batten
# Date   : August 30, 2012
#

import argparse
import sys
import re

from pymtl import *

from RegIncrFlat import RegIncrFlat

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )
  p.add_argument( "-v", "--verbose", action="store_true" )
  p.add_argument( "-h", "--help",    action="store_true" )
  p.add_argument( "input", type=int )
  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  model = RegIncrFlat()
  model.elaborate()

  sim = SimulationTool( model )
  sim.reset()

  model.in_.value = opts.input

  sim.cycle()
  sim.cycle()
  sim.cycle()

  print model.out.value

main()

