#!/bin/bash

if [ ! -d "dep" ]; then
  mkdir dep
fi

if [ ! -d "obj" ]; then
  mkdir obj
fi

if [ ! -d "bin" ]; then
  mkdir bin
fi

if [ ! -d "dump" ]; then
  mkdir dump
fi

if [ ! -d "vmh" ]; then
  mkdir vmh
fi

mv ubmark* bin/
mv bin/ubmark*.* dep/
mv dep/ubmark-config.h .
mv dep/ubmark.mk .
mv *.a dep/
mv dep/ubmark*.o obj/
for x in bin/*;do maven-objdump -DC --disassemble-zeroes --section=.text --section=.data --section=.sdata --section=.xcpthandler --section=.init --section=.fini --section=.ctors --section=.dtors --section=.eh_frame --section=.jcr --section=.sbss --section=.bss --section=.rodata $x > $x.dump;done
mv bin/*.dump dump/
for x in dump/*;
do
sed -i "" -e '
/<\_start>/ i\
00000400 <_bootstrap>:\
\   00400:  3c1d0007 	lui	sp,0xf\
\   00404:	341dfffc 	ori	sp,0,4095\
\   00408:	08000400 	j	1000\
\
' $x;
sed -i "" -e '
/1008:/ c\
\    1008:	08000408 	j	1020
' $x;
python ../scripts/objdump2vmh.py -f $x;
done
mv dump/*.vmh vmh/
