#!/usr/bin/env python
#=========================================================================
# pex-gcd-sim [options] <in0> <in1>
#=========================================================================
#
#  -h --help           Display this message
#  -v --verbose        Verbose mode
#
#  --impl              Choose model implementation (default bl)
#                       bl     : behavioral-level model
#                       rtl    : register-transfer-level model
#
#  --dump-vcd          Dump vcd to dump.vcd
#  --dump-vcd <fname>  Dump vcd to given file name <fname>
#
# The GCD simulator. Provide a list of two integers on the command line
# and the simulator will return the greatest common divisor.
#
# Author : Christopher Batten
# Date   : August 30, 2012
#

from __future__ import print_function

import argparse
import sys
import re

from pymtl import *

from GcdUnitBL  import GcdUnitBL
from GcdUnitRTL import GcdUnitRTL

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-v", "--verbose", action="store_true" )
  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="bl",
    choices=["bl","rtl"] )

  p.add_argument( "--dump-vcd", nargs='?',
                  default=False, const="dump.vcd" )

  p.add_argument( "in0", type=int )
  p.add_argument( "in1", type=int )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  # Determine which model to use in the simulator

  model_impl_dict = {
    'bl'     : GcdUnitBL,
    'rtl'    : GcdUnitRTL,
  }

  # Instantiate and elaborate the model

  model = model_impl_dict[ opts.impl ]()
  model.elaborate()

  # Create a simulator using the simulation tool

  sim = SimulationTool( model )

  # Turn on vcd dumping

  if opts.dump_vcd:
    sim.dump_vcd(opts.dump_vcd)

  # Reset the simulator

  sim.reset()

  # Set the input from the command line

  model.in_msg.value  = ( opts.in0 << 32 | opts.in1 )
  model.in_val.value  = True
  model.out_rdy.value = True

  # Tick the simulator for a couple of cycles and print line trace

  while not model.out_val.value:
    if opts.verbose:
      sim.print_line_trace()
    sim.cycle()

  # Add a couple extra ticks so that the VCD dump is nicer

  if opts.verbose:
    sim.print_line_trace()

  model.out_rdy.value = False

  sim.cycle()
  sim.cycle()
  sim.cycle()

  # Display the final output from the simulator

  print( model.out_msg )

main()

